pipeline { 
    agent any 

    stages{
        stage('Checkout') 
        {
            steps{
                checkout scm 
            }
        }

        stage('Pull Git'){
            steps{
                git 'https://github.com/CodeDetector/spe-major-project.git'
            }
        }

        stage('Build'){
            steps{
                dir('server'){
                    bat 'yarn start'
                }
            }
        }
        stage('Test'){
            steps{
                dir('party-owl'){
                    bat 'yarn test'
                }
            }
        }
        stage('Docker Build') {
            steps {
                bat 'docker-compose build'
                bat 'docker-compose up -d'
            }
        }
    }
}